### ISSUE TITLE
Unexpected error while acquiring application default credentials: Could not load the default credentials

### ISSUE THREAD

**Issue by Jengas** [googleapis/nodejs-text-to-speech#17]
(node:30216) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (C:\Users\Jengas\Documents\GitHub\esmod-discord\node_modules\google-auth-library\build\src\auth\googleauth.js:235:31)
    at step (C:\Users\Jengas\Documents\GitHub\esmod-discord\node_modules\google-auth-library\build\src\auth\googleauth.js:47:23)
    at Object.next (C:\Users\Jengas\Documents\GitHub\esmod-discord\node_modules\google-auth-library\build\src\auth\googleauth.js:28:53)
    at fulfilled (C:\Users\Jengas\Documents\GitHub\esmod-discord\node_modules\google-auth-library\build\src\auth\googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:30216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by phamhathanh** [comment]
I fixed this by setting GOOGLE_APPLICATION_CREDENTIALS to path of the credentials file.

**Comment by Jengas** [comment]
Thanks, @phamhathanh
