### ISSUE TITLE
Bandwidth exhausted

### ISSUE THREAD

**Issue by BuffMcBigHuge** [googleapis/nodejs-text-to-speech#347]
When running sequential asynchronous requests to the API, I encounter: 
`UnhandledPromiseRejectionWarning: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted`

Upon checking the GCP text to speech quotas, I see I am nowhere near the limit. Reference: https://console.cloud.google.com/apis/api/texttospeech.googleapis.com/quotas

#### Environment details

  - OS: macOS Catalina 10.15.3
  - Node.js version: v11.11.0
  - npm version: 6.13.6
  - `@google-cloud/text-to-speech` version: ^2.2.0

#### Steps to reproduce

Running the following function:

```
const processThings = async ()=> {

    const q = require('q');
    const async = require('async');
    const _ = require('underscore');
    const textToSpeech = require('@google-cloud/text-to-speech');

    process.env['GOOGLE_APPLICATION_CREDENTIALS'] = __dirname + '/x.json';
    const client = new textToSpeech.TextToSpeechClient();

    let things = await getThings();

    if (things.length == 0)
        return console.log('No things found');

    console.log(`Processing ${things.length} things`);

    async.series(_.map(things, (thing)=> {

        return (callback)=> {

            let retrieveMP3s = ()=> {

                return q.all(_.map(thing.data, (data, index)=> {

                    let promise = ()=> {

                        let deferred = q.defer();

                        setTimeout(async ()=> {
                    
                            const request = {
                                input: {text: data},
                                voice: {languageCode: 'en-US', ssmlGender: 'NEUTRAL'},
                                audioConfig: {audioEncoding: 'MP3'},
                            };

                            const [response] = await client.synthesizeSpeech(request);

                            if (!response || !response.audioContent)
                                return deferred.reject('Missing response: ' + JSON.stringify(response));
                            else if (response.audioContent instanceof Buffer) {
                                // Do something with audioContent;
                                deferred.resolve();
                            }
                            else
                                deferred.reject('Not a buffer');
                        }, index*1000);

                        return deferred.promise;
                    };

                    return promise();
                }));
            };

            let promises = [retrieveMP3s()];

            q.all(promises).then(()=> {

                thing.save((err)=> {
                    if (err)
                        return callback(err, null);
        
                    callback(null, 1);
                });
            }, (err)=> {
                callback(err, null);
            });
        };

    }), (err, results)=> {
        if (err)
            return console.error('END ERROR', err);

        console.log('Completed: ', results.length);
    });
}();
```

I understand I'm using q, async and _, and not all ES6 functionality, but this method works well for me for other similar looping utilities. For this function in particular, the process runs for a few minutes, works well, and then hangs on:

```
UnhandledPromiseRejectionWarning: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
    at Object.callErrorFromStatus (/Users/BioNetTech/BioNetGit/acadiumAPI/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/Users/BioNetTech/BioNetGit/acadiumAPI/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:202:15)
    at Http2CallStream.EventEmitter.emit (domain.js:446:20)
    at process.nextTick (/Users/BioNetTech/BioNetGit/acadiumAPI/node_modules/@grpc/grpc-js/build/src/call-stream.js:97:22)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

**Comment by BuffMcBigHuge** [comment]
Upgrading to Node v13.8.0 seemed to have solved my issue.
