### ISSUE TITLE
INVALID_ARGUMENT: No TTS voice matching the TTS request. Please correct the voice selection params and try again.

### ISSUE THREAD

**Issue by bbaltatu** [googleapis/nodejs-text-to-speech#89]
Hi, I am developing an app that use gTTS library for nodejs that run in this way. I have a text. I split in phrases and send one by one. I receive this fallowing issues:

```
(1) Error: 3 INVALID_ARGUMENT: No TTS voice matching the TTS request. Please correct the voice selection params and try again.
```

```
(2) Code: 2 , details: 'Internal error' Mode details above
{ Error: 2 UNKNOWN: Internal error.
    at Object.exports.createStatusError (/Users/bogdan/Work/NodeJS/abigail/backend/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/bogdan/Work/NodeJS/abigail/backend/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/bogdan/Work/NodeJS/abigail/backend/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/bogdan/Work/NodeJS/abigail/backend/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/bogdan/Work/NodeJS/abigail/backend/node_modules/grpc/src/client_interceptors.js:841:24)
     code: 2,
     metadata: Metadata { _internal_repr: {} },
     details: 'Internal error.',
     note: 'Exception occurred in retry method that was not classified as transient' } }
```

The first error is very strange because the voiceConfig remain the same (is a function with a lop and the only parameter that is changed is the phrase) 

The second issue i don't know to solve.
Yesterday the API works ok.

#### Environment details

  - OS:
Mac OS
  - Node.js version:
8.11.3
  - npm version:
6.4.1
  - `@google-cloud/text-to-speech` version:
0.3.0

#### Steps to reproduce

Just run multiple time .

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Pinging @googleapis/ml-apis for assistance on this one :)

**Comment by nnegrey** [comment]
Hi, just to get more context on this, you said you're splitting your text into multiple phrases?

Is that like a single word per request?
Are you sending more that 300 requests or are they all happening simultaneously?
About how many requests are you sending until you start seeing this issue?

**Comment by beccasaurus** [comment]
Closing. May re-open given response and additional reproduction information
